version: '3'

services:
    app:
        build: .
        ports:
          - 8080:8080
        container_name: sample_app
        volumes:
            - ./:/go
        tty: true
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        container_name: sample_db
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: sample
          MYSQL_USER: root
          MYSQL_PASSWORD: password
        ports:
          - "3306:3306"
